/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
    `maven-publish`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
    jcenter()
    maven { setUrl("https://plugins.gradle.org/m2/") }
}

val projectGroup = "tn.ksoftwares.hexagonal"

gradlePlugin {
    plugins {
        create("common-convention") {
            id = "$projectGroup.common"
            implementationClass = "$projectGroup.plugin.CommonConventionPlugin"
        }
        create("kotlin-library-convention") {
            id = "$projectGroup.kotlin-library"
            implementationClass = "$projectGroup.plugin.KotlinLibraryConventionPlugin"
        }
        create("application-convention") {
            id = "$projectGroup.application"
            implementationClass = "$projectGroup.plugin.ApplicationConventionPlugin"
        }
        create("android-library") {
            id = "$projectGroup.android-library"
            implementationClass = "$projectGroup.plugin.AndroidLibraryConventionPlugin"
        }
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:${PluginVersions.KOTLIN_VERSION}")
}

group = projectGroup
version = "1.0.0"
